import Link from "next/link";
import { IconAlertTriangle, IconChecklist, IconClock, IconFileDescription, IconProgress, IconRosetteDiscountCheck, IconUserQuestion } from "@tabler/icons-react";
import { getDashboardMetrics, getReportList, getStaffChartData } from "@/lib/queries";
import { MetricCard } from "@/components/dashboard/metric-card";
import { StaffCharts } from "@/components/staff/staff-charts";
import { ReportStatusBadge } from "@/components/reports/report-status-badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default async function StaffDashboardPage() {
  const [metrics, charts, pending] = await Promise.all([getDashboardMetrics(), getStaffChartData(), getReportList({ status: "pending" })]);
  return <div><div className="flex items-end justify-between"><div><p className="text-sm text-muted-foreground">ศูนย์ปฏิบัติการชุมชน</p><h1 className="mt-1 text-3xl font-bold">ภาพรวมการดำเนินงาน</h1></div><Link href="/staff/reports" className={buttonVariants()}>จัดการรายงาน</Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><MetricCard label="รายงานทั้งหมด" value={metrics.total} icon={IconFileDescription} /><MetricCard label="รอตรวจสอบ" value={metrics.pending} icon={IconClock} /><MetricCard label="ยังไม่มอบหมาย" value={metrics.unassigned} icon={IconUserQuestion} /><MetricCard label="รับเรื่อง/กำลังดำเนินการ" value={metrics.inProgress} icon={IconProgress} /><MetricCard label="เร่งด่วน" value={metrics.urgent} icon={IconAlertTriangle} /><MetricCard label="แก้ไขแล้ววันนี้" value={metrics.resolvedToday} icon={IconRosetteDiscountCheck} /></div><div className="mt-6"><StaffCharts {...charts} /></div><Card className="mt-6"><CardHeader className="flex-row items-center justify-between"><CardTitle className="flex items-center gap-2"><IconChecklist className="text-primary" /> รายงานที่รอตรวจสอบ</CardTitle><Link href="/staff/reports?status=pending" className={buttonVariants({ variant: "ghost", size: "sm" })}>ดูทั้งหมด</Link></CardHeader><CardContent>{pending.items.length ? <div className="divide-y">{pending.items.slice(0, 6).map((report) => <Link key={report.id} href={`/staff/reports/${report.id}`} className="flex items-center gap-4 py-3 first:pt-0 last:pb-0"><span className="hidden font-mono text-xs text-primary sm:block">{report.reportNumber}</span><span className="min-w-0 flex-1 truncate font-medium">{report.title}</span><ReportStatusBadge status={report.status} /></Link>)}</div> : <div className="py-10 text-center"><p className="font-medium">ไม่มีรายงานที่รอตรวจสอบ</p><p className="text-sm text-muted-foreground">รายงานทั้งหมดได้รับการตรวจสอบแล้ว</p></div>}</CardContent></Card></div>;
}
